[project]
name = "soumyadeep-chakravarti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Soumyadeep Chakravarti", email = "soumyadeepsai1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.2",
    "onnxruntime>=1.28.0",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "rembg>=2.0.78",
]

[project.scripts]
soumyadeep-chakravarti = "soumyadeep_chakravarti:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
